module.exports = {
  apps: [
    {
      name: "zapmatic-bot-worker-all",
      script: "spark",
      args: "bot:all",
      interpreter: "php",
      cwd: "/www/wwwroot/app_zapmatic_app",
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      watch: false,
      max_memory_restart: "256M",
      error_file: "writable/logs/pm2-all-error.log",
      out_file: "writable/logs/pm2-all-out.log",
    },
    {
      name: "zapmatic-call-worker",
      script: "spark",
      args: "call:campaigns",
      interpreter: "php",
      cwd: "/www/wwwroot/app_zapmatic_app",
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      watch: false,
      max_memory_restart: "128M",
      error_file: "writable/logs/pm2-call-error.log",
      out_file: "writable/logs/pm2-call-out.log",
    },
    {
      name: "zapmatic-gmscraper",
      script: "index.js",
      interpreter: "node",
      cwd: "/www/wwwroot/app_zapmatic_app/app_zapmatic_scraper",
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      watch: false,
      max_memory_restart: "256M",
    },
    {
      name: "zapmatic-cloud-campaign-worker",
      script: "spark",
      args: "cloud:campaigns",
      interpreter: "php",
      cwd: "/www/wwwroot/app_zapmatic_app",
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      watch: false,
      max_memory_restart: "128M",
      error_file: "writable/logs/pm2-cloud-campaign-error.log",
      out_file: "writable/logs/pm2-cloud-campaign-out.log",
    },
  ]
};
