module.exports = {
  apps: [
    {
      name: "bot-worker-debounce",
      script: "spark",
      args: "bot:debounce",
      interpreter: "php",
      cwd: "/www/wwwroot/app_zapmatic_app",
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      watch: false,
      max_memory_restart: "128M",
      error_file: "writable/logs/pm2-debounce-error.log",
      out_file: "writable/logs/pm2-debounce-out.log",
    },
    {
      name: "bot-worker-queue",
      script: "spark",
      args: "bot:queue",
      interpreter: "php",
      cwd: "/www/wwwroot/app_zapmatic_app",
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      watch: false,
      max_memory_restart: "128M",
      error_file: "writable/logs/pm2-queue-error.log",
      out_file: "writable/logs/pm2-queue-out.log",
    },
    {
      name: "bot-worker-sessions",
      script: "spark",
      args: "bot:sessions",
      interpreter: "php",
      cwd: "/www/wwwroot/app_zapmatic_app",
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      watch: false,
      max_memory_restart: "128M",
      error_file: "writable/logs/pm2-sessions-error.log",
      out_file: "writable/logs/pm2-sessions-out.log",
    },
    {
      name: "campaign-worker-dispatch",
      script: "spark",
      args: "campaign:dispatch",
      interpreter: "php",
      cwd: "/www/wwwroot/app_zapmatic_app",
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      watch: false,
      max_memory_restart: "256M",
      error_file: "writable/logs/pm2-campaign-error.log",
      out_file: "writable/logs/pm2-campaign-out.log",
    }
  ]
};
