-- WhatsApp Flows - Phase 1
-- Internal data model for Cloud-first rollout
-- Safe additive migration: no existing table/column is altered here

CREATE TABLE IF NOT EXISTS `sp_whatsapp_flow_endpoints` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `ids` VARCHAR(32) DEFAULT NULL,
  `team_id` INT(11) DEFAULT NULL,
  `account_id` INT(11) DEFAULT NULL,
  `account_ids` VARCHAR(255) DEFAULT NULL,
  `waba_id` VARCHAR(128) DEFAULT NULL,
  `phone_number_id` VARCHAR(128) DEFAULT NULL,
  `endpoint_uri` TEXT DEFAULT NULL,
  `endpoint_status` VARCHAR(32) NOT NULL DEFAULT 'not_configured',
  `public_key_fingerprint` VARCHAR(255) DEFAULT NULL,
  `public_key_uploaded` TINYINT(1) NOT NULL DEFAULT 0,
  `private_key_path` TEXT DEFAULT NULL,
  `app_secret_verified` TINYINT(1) NOT NULL DEFAULT 0,
  `last_meta_error` TEXT DEFAULT NULL,
  `last_sync_at` INT(11) DEFAULT NULL,
  `changed` INT(11) DEFAULT NULL,
  `created` INT(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_team_account` (`team_id`, `account_id`),
  KEY `idx_account_ids` (`account_ids`),
  KEY `idx_phone_number_id` (`phone_number_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `sp_whatsapp_flows` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `ids` VARCHAR(32) DEFAULT NULL,
  `team_id` INT(11) DEFAULT NULL,
  `account_id` INT(11) DEFAULT NULL,
  `account_ids` VARCHAR(255) DEFAULT NULL,
  `waba_id` VARCHAR(128) DEFAULT NULL,
  `phone_number_id` VARCHAR(128) DEFAULT NULL,
  `meta_flow_id` VARCHAR(128) DEFAULT NULL,
  `endpoint_id` INT(11) DEFAULT NULL,
  `name` VARCHAR(255) NOT NULL,
  `slug` VARCHAR(255) DEFAULT NULL,
  `channel` VARCHAR(32) NOT NULL DEFAULT 'cloud_api',
  `status_local` VARCHAR(32) NOT NULL DEFAULT 'draft',
  `status_meta` VARCHAR(32) DEFAULT NULL,
  `json_version` VARCHAR(32) DEFAULT NULL,
  `data_api_version` VARCHAR(32) DEFAULT NULL,
  `flow_json` LONGTEXT DEFAULT NULL,
  `preview_data` LONGTEXT DEFAULT NULL,
  `health_status` LONGTEXT DEFAULT NULL,
  `last_meta_error` TEXT DEFAULT NULL,
  `published_at` INT(11) DEFAULT NULL,
  `last_sync_at` INT(11) DEFAULT NULL,
  `changed` INT(11) DEFAULT NULL,
  `created` INT(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_team_ids` (`team_id`, `ids`),
  KEY `idx_team_account` (`team_id`, `account_id`),
  KEY `idx_account_ids` (`account_ids`),
  KEY `idx_meta_flow` (`meta_flow_id`),
  KEY `idx_status` (`team_id`, `status_local`, `status_meta`),
  KEY `idx_endpoint` (`endpoint_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `sp_whatsapp_flow_assets` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `ids` VARCHAR(32) DEFAULT NULL,
  `team_id` INT(11) DEFAULT NULL,
  `flow_id` INT(11) DEFAULT NULL,
  `meta_flow_id` VARCHAR(128) DEFAULT NULL,
  `meta_asset_id` VARCHAR(128) DEFAULT NULL,
  `meta_asset_handle` VARCHAR(255) DEFAULT NULL,
  `name` VARCHAR(255) NOT NULL,
  `asset_type` VARCHAR(32) NOT NULL DEFAULT 'other',
  `mime_type` VARCHAR(191) DEFAULT NULL,
  `storage_path` TEXT DEFAULT NULL,
  `public_url` TEXT DEFAULT NULL,
  `checksum` VARCHAR(128) DEFAULT NULL,
  `status` VARCHAR(32) NOT NULL DEFAULT 'local',
  `sort_order` INT(11) NOT NULL DEFAULT 0,
  `last_meta_error` TEXT DEFAULT NULL,
  `changed` INT(11) DEFAULT NULL,
  `created` INT(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_flow` (`flow_id`, `team_id`),
  KEY `idx_meta_flow` (`meta_flow_id`),
  KEY `idx_asset_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `sp_whatsapp_flow_events` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `team_id` INT(11) DEFAULT NULL,
  `flow_id` INT(11) DEFAULT NULL,
  `endpoint_id` INT(11) DEFAULT NULL,
  `account_id` INT(11) DEFAULT NULL,
  `account_ids` VARCHAR(255) DEFAULT NULL,
  `instance_id` VARCHAR(255) DEFAULT NULL,
  `event_type` VARCHAR(64) NOT NULL,
  `direction` VARCHAR(16) DEFAULT NULL,
  `contact_id` VARCHAR(128) DEFAULT NULL,
  `chat_id` VARCHAR(128) DEFAULT NULL,
  `flow_token` VARCHAR(255) DEFAULT NULL,
  `message_id` VARCHAR(255) DEFAULT NULL,
  `status` VARCHAR(64) DEFAULT NULL,
  `payload` LONGTEXT DEFAULT NULL,
  `response` LONGTEXT DEFAULT NULL,
  `error_message` TEXT DEFAULT NULL,
  `created` INT(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_team_event` (`team_id`, `event_type`, `created`),
  KEY `idx_flow` (`flow_id`, `created`),
  KEY `idx_account` (`account_id`, `account_ids`),
  KEY `idx_message` (`message_id`),
  KEY `idx_token` (`flow_token`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
